### ISSUE TITLE
SparkIntegrationTest: Execution package of goal net.wouterdanes.docker:docker-maven-plugin:5.0.0:build-images failed: Not a JSON Object: "client"

### ISSUE THREAD

**Issue by abhitechdojo** [wouterd/docker-maven-plugin#112]
Here is my pom.xml for the docker-maven-plugin

>             <plugin>
>                <groupId>net.wouterdanes.docker</groupId>
>                <artifactId>docker-maven-plugin</artifactId>
>                <version>5.0.0</version>
>                <executions>
                    <execution>
                        <id>package</id>
                        <goals>
                            <goal>build-images</goal>
                        </goals>
                        <configuration>
                            <images>
                                <image>
                                    <id>cloudera</id>
                                    <dockerFile>${project.basedir}/src/integration-test/docker/Dockerfile</dockerFile>
                                    <artifacts>
                                        <artifact>
                                            <file>${project.build.directory}/${project.build.finalName}.jar</file>
                                        </artifact>
                                    </artifacts>
                                </image>
                            </images>
                        </configuration>
                    </execution>
                    <execution>
                        <id>start</id>
                        <goals>
                            <goal>start-containers</goal>
                        </goals>
                        <configuration>
                            <forceCleanup>true</forceCleanup>
                            <containers>
                                <container>
                                    <id>cloudera</id>
                                    <image>cloudera/quickstart</image>
                                    <waitForStartup>Ratpack started for</waitForStartup>
                                </container>
                            </containers>
                        </configuration>
                    </execution>
                    <execution>
                        <id>stop</id>
                        <goals>
                            <goal>stop-containers</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>verify</id>
                        <goals>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

but when I run this using `mvn clean verify` I get an error

>[DEBUG] Configuring mojo 'net.wouterdanes.docker:docker-maven-plugin:5.0.0:build-images' with >basic configurator -->
>[DEBUG]   (s) id = cloudera/quickstart
>[DEBUG]   (s) dockerFile = /Users/abhishek.srivastava/MyProjects/SparkIntegrationTests/src/integration-test/docker/Dockerfile
[DEBUG]   (s) file = /Users/abhishek.srivastava/MyProjects/SparkIntegrationTests/target/SparkIntegrationTest-1.0-SNAPSHOT.jar
[DEBUG]   (s) artifacts = [net.wouterdanes.docker.provider.model.Artifact@37e31a6e]
[DEBUG]   (s) images = [net.wouterdanes.docker.provider.model.ImageBuildConfiguration@5f090522]
[DEBUG]   (s) providerName = remote
[DEBUG]   (f) remoteRepositories = [ddc-artifactory-as-mirror (http://artifactory.int.dealer.com/artifactory/all-repos, default, releases+snapshots)]
[DEBUG]   (f) repositorySystemSession = org.eclipse.aether.DefaultRepositorySystemSession@1a2f1788
[DEBUG]   (s) skip = false
[DEBUG]   (f) settings = org.apache.maven.execution.SettingsAdapter@2c3574d1
[DEBUG] -- end configuration --
[INFO] Using docker provider: remote
**[INFO] Building image 'cloudera/quickstart'..
**[DEBUG] No user name provided. Will try <servers> from settings.xml
**[DEBUG] Cannot find server null in Maven settings**
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:26 min
[INFO] Finished at: 2016-04-14T20:36:28-05:00
[INFO] Final Memory: 52M/810M
[INFO] ------------------------------------------------------------------------
>[ERROR] Failed to execute goal net.wouterdanes.docker:docker-maven-plugin:5.0.0:build-images 
>(package) on project SparkIntegrationTest: Execution package of goal net.wouterdanes.docker:docker->maven-plugin:5.0.0:build-images failed: Not a JSON Object: "client" -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.wouterdanes.docker:docker-maven-plugin:5.0.0:build-images (package) on project SparkIntegrationTest: Execution package of goal net.wouterdanes.docker:docker-maven-plugin:5.0.0:build-images failed: Not a JSON Object: "client"
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution package of goal net.wouterdanes.docker:docker-maven-plugin:5.0.0:build-images failed: Not a JSON Object: "client"
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.IllegalStateException: Not a JSON Object: "client"
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
	at net.wouterdanes.docker.remoteapi.MiscService.parseSteamForImageId(MiscService.java:153)
	at net.wouterdanes.docker.remoteapi.MiscService.buildImage(MiscService.java:134)
	at net.wouterdanes.docker.provider.RemoteApiBasedDockerProvider.buildImage(RemoteApiBasedDockerProvider.java:99)
	at net.wouterdanes.docker.maven.BuildImageMojo.doExecute(BuildImageMojo.java:60)
	at net.wouterdanes.docker.maven.AbstractDockerMojo.execute(AbstractDockerMojo.java:120)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by abhitechdojo** [comment]
I was able to resolve this issue. The docker toolkit on my mac was not the right version. The error is resolved when I upgrade the docker version to 

Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:13:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64
