### ISSUE TITLE
'images' for goal missing or invalid

### ISSUE THREAD

**Issue by xcurry** [wouterd/docker-maven-plugin#63]
```xml
  <build>
    <plugins>
      <plugin>
        <groupId>net.wouterdanes.docker</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>3.0</version>
        <executions>
          <execution>
            <id>build</id>
            <goals>
              <goal>build-images</goal>
            </goals>
            <configuration>
              <images>
                <image>
                  <id>test</id>
                  <dockerFile>src/main/resources/Dockerfile</dockerFile>
                </image>
              </images>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

gives a

`
Caused by: org.apache.maven.plugin.PluginParameterException: The parameters 'images' for goal net.wouterdanes.docker:docker-maven-plugin:3.0:build-images are missing or invalid
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:584)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:537)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:119)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
`

for `mvn docker:build-images`

Can't figure out what is missing.

**Comment by wouterd** [comment]
Hi!

Weird, I took your snippet and it ran fine. What version of maven are you using?

Here's the full POM of what I ran:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>nl.wouter</groupId>
  <artifactId>test</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>test</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>net.wouterdanes.docker</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>3.0</version>
        <executions>
          <execution>
            <id>build</id>
            <goals>
              <goal>build-images</goal>
            </goals>
            <configuration>
              <images>
                <image>
                  <id>test</id>
                  <dockerFile>src/main/resources/Dockerfile</dockerFile>
                </image>
              </images>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```

**Comment by xcurry** [comment]
```
mvn -v
Apache Maven 3.2.2 (NON-CANONICAL_2015-02-16T16:18:37_mockbuild; 2015-02-16T08:18:37-08:00)
Maven home: /usr/share/maven
Java version: 1.8.0_31, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.31-5.b13.fc21.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.18.7-200.fc21.x86_64", arch: "amd64", family: "unix"

I also ran your pom.xml with similar results. I also tried maven 3.2.5 with no luck.

**Comment by xcurry** [comment]
`mvn clean install` works, but `mvn docker:build-images` fails both for my original case and your skeleton pom.xml

**Comment by wouterd** [comment]
Ahh, ok, I see now. :)

The build-images phase is bound to the package phase by default. You can change that, but it shouldn't be necessary in general.
A simple `mvn clean package` should work. 

This should also work: `mvn net.wouterdanes.docker:docker-maven-plugin:build-images`, but then the POM needs to look like this, with configuration pulled out of the executions block. Don't know why really..

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>nl.wouter</groupId>
  <artifactId>test</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>test</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>net.wouterdanes.docker</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>3.0</version>
        <configuration>
          <images>
            <image>
              <id>test</id>
              <dockerFile>src/main/resources/Dockerfile</dockerFile>
            </image>
          </images>
        </configuration>
        <executions>
          <execution>
            <id>build</id>
            <goals>
              <goal>build-images</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```
