### ISSUE TITLE
Unable to Add resource

### ISSUE THREAD

**Issue by nickcodefresh** [wouterd/docker-maven-plugin#66]
I'm trying to build an image and have the following as my Dockerfile

```
FROM java:8
EXPOSE 9092
ADD content-link-service-*.jar app.jar
```

When I run this I get the following output 

```
[ERROR] Cannot build image 'content-link-service'
net.wouterdanes.docker.remoteapi.exception.DockerException: Can't obtain ID from build output stream.
	at net.wouterdanes.docker.remoteapi.MiscService.buildImage(MiscService.java:74)
	at net.wouterdanes.docker.provider.RemoteApiBasedDockerProvider.buildImage(RemoteApiBasedDockerProvider.java:100)
	at net.wouterdanes.docker.maven.BuildImageMojo.doExecute(BuildImageMojo.java:60)
	at net.wouterdanes.docker.maven.AbstractDockerMojo.execute(AbstractDockerMojo.java:86)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] Api response:
{"stream":"Step 0 : FROM java:8\n"}
{"stream":" ---\u003e 64fb28226dbe\n"}
{"stream":"Step 1 : EXPOSE 9092\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 726eb601d9fd\n"}
{"stream":"Step 2 : ADD content-link-service-*.jar app.jar\n"}
{"errorDetail":{"message":"No source files were specified"},"error":"No source files were specified"}
```

What am I doing wrong here? If I get rid of the Add it works fine.

Thanks

Nick

**Comment by nickcodefresh** [comment]
It's ok I figured it out. I need to add an artifact in the POM which I can then reference from the Dockerfile

```
<plugin>
	<groupId>net.wouterdanes.docker</groupId>
        <artifactId>docker-maven-plugin</artifactId>
	<version>3.0</version>
	<configuration>
		<images>
			<image>
				<id>content-link-service</id>
				<dockerFile>${project.basedir}/src/main/docker/Dockerfile</dockerFile>
				<nameAndTag>${project.artifactId}</nameAndTag>
				<artifacts>
					<artifact>
						<file>${project.basedir}/target/${project.artifactId}-${project.version}.jar</file>
						<dest>${project.artifactId}.jar</dest>
					</artifact>
				</artifacts>
				<keep>true</keep>
			</image>
		</images>
	</configuration>
</plugin>
```

And in the Dockerfile

```
FROM java:8
EXPOSE 9092

ADD content-link-service.jar app.jar
```

**Comment by wouterd** [comment]
awesome. :) Did the documentation help you solve this or does that need work?

**Comment by nickcodefresh** [comment]
It needs work, as it baffled me for a good few hours.
