### ISSUE TITLE
Sample POM XML doesn't work

### ISSUE THREAD

**Issue by nickcodefresh** [wouterd/docker-maven-plugin#67]
I've been trying to use the sample POM XML for my project:

```
			<plugin>
				<groupId>net.wouterdanes.docker</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>3.0</version>
				<configuration>
					<userName>....</userName>
					<password>....</password>
					<email>....</email>
				</configuration>
				<executions>
					<execution>
						<id>build</id>
						<goals>
							<goal>build-images</goal>
						</goals>
						<configuration>
							<images>
								<image>
									<id>content-link-service</id>
									<dockerFile>${project.basedir}/src/main/docker/Dockerfile</dockerFile>
									<nameAndTag>nickcodefresh/content-link-service:${project.version}</nameAndTag>
									<artifacts>
										<artifact>
											<file>${project.basedir}/target/${project.artifactId}-${project.version}.jar</file>
											<dest>${project.artifactId}.jar</dest>
										</artifact>
									</artifacts>
									<keep>true</keep>
									<push>true</push>
									<registry>https://registry.hub.docker.com</registry>
								</image>
							</images>
						</configuration>
					</execution>
					<execution>
						<id>start</id>
						<configuration>
							<containers>
								<container>
									<id>Debian</id>
									<image>debian:wheezy</image>
								</container>
								<container>
									<id>BusyBox</id>
									<image>busybox</image>
									<hostname>busyhost</hostname>
								</container>
								<container>
									<id>cache</id>
									<image>nginx</image>
								</container>
							</containers>
						</configuration>
						<goals>
							<goal>start-containers</goal>
						</goals>
					</execution>
					<execution>
						<id>push</id>
						<goals>
							<goal>push-images</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

When I run mvn -X docker:build-images I'm getting the error:

```
[ERROR] Failed to execute goal net.wouterdanes.docker:docker-maven-plugin:3.0:build-images (default-cli) on project content-link-service: The parameters 'images' for goal net.wouterdanes.docker:docker-maven-plugin:3.0:build-images are missing or invalid -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.wouterdanes.docker:docker-maven-plugin:3.0:build-images (default-cli) on project content-link-service: The parameters 'images' for goal net.wouterdanes.docker:docker-maven-plugin:3.0:build-images are missing or invalid
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:220)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginParameterException: The parameters 'images' for goal net.wouterdanes.docker:docker-maven-plugin:3.0:build-images are missing or invalid
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:665)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:618)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
```

Is the sample POM XML valid? It doesn't appear to be to me

**Comment by nickcodefresh** [comment]
This is driving me nuts. I'm using the latest release version of the plugin and have tried with both docker 1.3 and 1.6. It's almost like it's a maven issue though.

**Comment by dverbeek84** [comment]
Same issue here.

**Comment by ypandit** [comment]
Same issue for me!

**Comment by wouterd** [comment]
Thanks for the feedback! And sorry for the broken example and the long wait.
I have updated the example with one from one of my integration tests, that one works.
Please let me know if anything is unclear, I'll help you guys out and update the docs.
