### ISSUE TITLE
Problems running Eureka and Feign with Docker plugin

### ISSUE THREAD

**Issue by nickcodefresh** [wouterd/docker-maven-plugin#69]
Hi,

I'm trying to use the plugin when running my integration tests. I have it configured to start an instance of Eureka and my service:

```
<configuration>
	<containers>
		<container>
			<id>eureka</id>
			<image>dockerhub.myradio.thisisglobal.com/eureka:latest</image>
			<waitForStartup>Started EurekaApplication</waitForStartup>
			<hostname>eureka</hostname>
		</container>
		<container>
			<id>content-link-service</id>
			<image>dockerhub.myradio.thisisglobal.com/content-link-service:latest</image>
			<env>
				<spring.profiles.active>docker-integration-tests</spring.profiles.active>
			</env>
			<waitForStartup>registration status: 204</waitForStartup>
			<hostname>content-link-service</hostname>
			<links>
				<link>
					<containerId>eureka</containerId>
					<containerAlias>eureka</containerAlias>
				</link>
			</links>
		</container>
<configuration>
```

When running `mvn clean verify` I can see docker has started the 2 containers and exposed the relevant ports:

```
CONTAINER ID        IMAGE                                                            COMMAND                CREATED              STATUS              PORTS                                                                                                NAMES
a7a934f5affa        dockerhub.myradio.thisisglobal.com/content-link-service:latest   "java -Djava.securit   About a minute ago   Up About a minute   0.0.0.0:33061->9092/tcp                                                                              prickly_darwin         
55bbb289f146        dockerhub.myradio.thisisglobal.com/eureka:latest                 "java -Djava.securit   2 minutes ago        Up 2 minutes        0.0.0.0:33057->8761/tcp, 0.0.0.0:33060->9092/tcp   backstabbing_pasteur   
```
I'm not sure why the Eureka container has also exposed the service port 9092 though. When I run my code and Feign tries to connect the service via Eureka I get the exception:

```
java.lang.RuntimeException: com.netflix.client.ClientException: Load balancer does not have available server for client: content-link-service
	at feign.ribbon.RibbonClient.execute(RibbonClient.java:75)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:92)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:71)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:94)
	at com.sun.proxy.$Proxy95.getStations(Unknown Source)
	at com.globalradio.myradio.admingateway.controller.StationsController.getStations(StationsController.java:34)
```

Any ideas why this might be happening? I know the infrastructure works fine, as the tests execute fine if I start the containers manually:

```
docker run -d -p 8761:8761 --name eureka dockerhub.myradio.thisisglobal.com/eureka
docker run -d -p 9090:9090 --name station-service --link eureka:eurkea -e spring.profiles.active=docker-integration-tests dockerhub.myradio.thisisglobal.com/content-link-service
```

```
CONTAINER ID        IMAGE                                                            COMMAND                CREATED             STATUS              PORTS                                                  NAMES
ee1d03c40fe7        dockerhub.myradio.thisisglobal.com/content-link-service:latest   "java -Djava.securit   18 seconds ago      Up 16 seconds       0.0.0.0:9092->9092/tcp                                 content-link-service   
ad83909eacdd        dockerhub.myradio.thisisglobal.com/eureka:latest                 "java -Djava.securit   21 seconds ago      Up 20 seconds       9092/tcp, 0.0.0.0:8761->8761/tcp   eureka             
```

Notice that this time the Eureka container hasn't exposed the 9092 port.

**Comment by abhijitsarkar** [comment]
This is not a problem with the docker maven plugin. You've a runtime failure from Eureka. How's that related to the docker plugin that is only used to build the image?
Did you find out a solution to your problem?
