### ISSUE TITLE
Cannot copy to image

### ISSUE THREAD

**Issue by jarmoni** [wouterd/docker-maven-plugin#77]
File 'docker-entrypoint.sh' is in the same folder as the Dockerfile. Execution of 'docker build' in console works as expected. Maybe a path problem?
By the way: It is imho not a good idea that Maven finished with "BUILD SUCCESS" although the
image-creation did non succeed.....
```
Step 7 : COPY docker-entrypoint.sh /docker-entrypoint.sh
ERROR: docker-entrypoint.sh: no such file or directory
[ERROR] Cannot build image 'cassandra'
net.wouterdanes.docker.remoteapi.exception.DockerException: Can't obtain ID from build output stream.
	at net.wouterdanes.docker.remoteapi.MiscService.buildImage(MiscService.java:85)
	at net.wouterdanes.docker.provider.RemoteApiBasedDockerProvider.buildImage(RemoteApiBasedDockerProvider.java:100)
	at net.wouterdanes.docker.maven.BuildImageMojo.doExecute(BuildImageMojo.java:60)
	at net.wouterdanes.docker.maven.AbstractDockerMojo.execute(AbstractDockerMojo.java:86)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:11 min
[INFO] Finished at: 2015-07-15T16:40:07+02:00
[INFO] Final Memory: 21M/484M
```

**Comment by wouterd** [comment]
Hi there!

Fully agree that build success when image build fails is a bug, I'll have a look at it.
The maven plugin works a bit different than the docker CLI when it comes to adding files, you need to specify each file that needs to go with the dockerfile in the plugin configuration like this:

```
<artifacts>
                <artifact>
                  <file>${project.basedir}/src/test/resources/nginx.conf</file>
                  <dest>etc/nginx/nginx.conf</dest>
                </artifact>
                <artifact>
                  <file>${project.basedir}/src/test/resources/sites-available/</file>
                  <dest>etc/nginx/sites-available/</dest>
                </artifact>
              </artifacts>
```

Reason for that is that docker-ignore files didn't exist yet when I made this plugin. It does seem a bit counter-intuitive now, will see if that can be fixed somewhere along the road. For now just add that file as an artifact and things should start working again. You still need to ADD it in the docker file.

**Comment by wouterd** [comment]
Have a look at the link below for an explanation of the build images part:
https://github.com/wouterd/docker-maven-plugin#build-images-goal

**Comment by wouterd** [comment]
About the build not failing, do you have the following snippet in your POM?

```
      <execution>
        <id>verify</id>
        <goals>
          <goal>verify</goal>
        </goals>
      </execution>
```

If you then do mvn clean verify, does your build still succeed? Reason why The build mojo itself is not failing immediately is because the stop container mojo still needs to do cleanup, but that runs in the post-integration-test phase.

**Comment by jarmoni** [comment]
Hmm, imho a bit error-prone to add files in both Dockerfile and POM.  But having a "working workaround" is much better than nothing at all ;-)

Concerning the wrong "BUILD SUCCESS":
You are right. Invoking the "verify"-goal solved the issue.

Thanks :-)

**Comment by wouterd** [comment]
You're welcome. :) There's currently no way to make maven execute a plugin by default, that's something that's only happening for standard maven plugins.

I'll look into making the build process more "standard docker", I kind of not really like the current way either.
