### ISSUE TITLE
BufferUnderflowException when starting container

### ISSUE THREAD

**Issue by moimael** [wouterd/docker-maven-plugin#88]
Hi,

I just installed your plugin and when starting my container I get this error:
```
Failed to execute goal net.wouterdanes.docker:docker-maven-plugin:4.1.0:start-containers (start) on project alinto-ui-webapp: Execution start of goal net.wouterdanes.docker:docker-maven-plugin:4.1.0:start-containers failed. BufferUnderflowException -> [Help 1]
```

Any thought ?

Thanks !

**Comment by wouterd** [comment]
Interesting! Can you start maven with -X to see if the logs show more?
Also, can you give me some insights into your POM?

**Comment by moimael** [comment]
The pom :

```xml
			<plugin>
			  <groupId>net.wouterdanes.docker</groupId>
			  <artifactId>docker-maven-plugin</artifactId>
			  <version>4.1.0</version>
			  <executions>
			    <execution>
			      <id>start</id>
			      <goals>
			        <goal>start-containers</goal>
			      </goals>
			      <configuration>
			        <forceCleanup>true</forceCleanup>
			        <containers>
			          <container>
			            <id>webmail</id>
			            <image>webmail-img</image>
			            <env>
			              <SPRING_PROFILE>integration</SPRING_PROFILE>
			            </env>
			            <waitForStartup>Server startup</waitForStartup>
			          </container>
			        </containers>
			      </configuration>
			    </execution>
			    <execution>
			      <id>stop</id>
			      <goals>
			        <goal>stop-containers</goal>
			      </goals>
			    </execution>
			    <execution>
			      <id>verify</id>
			      <goals>
			        <goal>verify</goal>
			      </goals>
			    </execution>
			  </executions>
			</plugin>
```

Maven output with -X : 
```
[ERROR] Failed to execute goal net.wouterdanes.docker:docker-maven-plugin:4.1.0:start-containers (start) on project alinto-ui-webapp: Execution start of goal net.wouterdanes.docker:docker-maven-plugin:4.1.0:start-containers failed. BufferUnderflowException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.wouterdanes.docker:docker-maven-plugin:4.1.0:start-containers (start) on project alinto-ui-webapp: Execution start of goal net.wouterdanes.docker:docker-maven-plugin:4.1.0:start-containers failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution start of goal net.wouterdanes.docker:docker-maven-plugin:4.1.0:start-containers failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.nio.BufferUnderflowException
	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
	at java.nio.ByteBuffer.get(ByteBuffer.java:715)
	at net.wouterdanes.docker.remoteapi.ContainersService.getLogs(ContainersService.java:91)
	at net.wouterdanes.docker.provider.RemoteApiBasedDockerProvider.getLogs(RemoteApiBasedDockerProvider.java:138)
	at net.wouterdanes.docker.maven.StartContainerMojo.waitForContainerToFinishStartup(StartContainerMojo.java:139)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.wouterdanes.docker.maven.StartContainerMojo.waitForContainersToFinishStartup(StartContainerMojo.java:125)
	at net.wouterdanes.docker.maven.StartContainerMojo.doExecute(StartContainerMojo.java:95)
	at net.wouterdanes.docker.maven.AbstractDockerMojo.execute(AbstractDockerMojo.java:95)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
```

**Comment by moimael** [comment]
Seems to happens with docker 1.8.1 and log-driver set to journald. Deleting journald driver option or upgrading (I tried 1.9.1) seems to work fine.

**Comment by wouterd** [comment]
Interesting issue, appears that the journald driver might have had a bug, because it's breaking the log protocol. It's reporting the wrong amount of characters to read. I'll try to guard against it a bit by not trusting the value it returns. :)
