### ISSUE TITLE
Unable to build a docker image with docker-machine version 0.6.0

### ISSUE THREAD

**Issue by Ardesco** [wouterd/docker-maven-plugin#96]
In the latest version of docker-machine they do not print:

    Successfully built 16cdd91fdafe

when you run a build in quiet mode (-q).

As a result the build always fails for me when I try to build an image because the plugin doesn't realise it has completed successfully (even though the image has been built).

**Comment by Ardesco** [comment]
Relevant log from my maven build:

`[INFO] --- docker-maven-plugin:4.1.1:build-images (build-rp-collector) @ rp-collector-docker ---
[INFO] Using docker provider: remote
[INFO] Building image 'rpc', with name and tag 'elsevier/rpc:rp-collector-DEV-SNAPSHOT'..
sha256:16cdd91fdafe26aad4d7e04d66aff1ab740ea11fcbc3b3a791760ec5f626d669
[ERROR] Cannot build image 'rpc'
net.wouterdanes.docker.remoteapi.exception.DockerException: Can't obtain ID from build output stream.
	at net.wouterdanes.docker.remoteapi.MiscService.buildImage(MiscService.java:124)
	at net.wouterdanes.docker.provider.RemoteApiBasedDockerProvider.buildImage(RemoteApiBasedDockerProvider.java:99)
	at net.wouterdanes.docker.maven.BuildImageMojo.doExecute(BuildImageMojo.java:60)
	at net.wouterdanes.docker.maven.AbstractDockerMojo.execute(AbstractDockerMojo.java:95)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] 
[INFO] --- docker-maven-plugin:4.1.1:verify (verify) @ rp-collector-docker ---
[INFO] Using docker provider: remote
[ERROR] The following plugin goals had errors: 
 - build-images

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.251 s
[INFO] Finished at: 2016-02-11T14:42:43+00:00
[INFO] Final Memory: 19M/649M
[INFO] ------------------------------------------------------------------------`

The output I get on a successful build is: 

    sha256:16cdd91fdafe26aad4d7e04d66aff1ab740ea11fcbc3b3a791760ec5f626d669

instead of: 

    Successfully built 16cdd91fdafe

**Comment by Ardesco** [comment]
I've had a look a the change you have made, and while it is great for me you are breaking backwards compatibility with old versions of docker.  Would this be better?

    Pattern.compile(".*(Successfully built |sha256:)([0-9a-f]+).*", Pattern.DOTALL);

**Comment by wouterd** [comment]
Hmm, you're right.. Good point. Going that regex should do it. Was debating something a bit more fancy like version detection, but I think I'll bump the major version soonish anyway to be able to get those build args going. :)
